{% set version = "1.19.3" %}

package:
  name: tabulator
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tabulator/tabulator-{{ version }}.tar.gz
  sha256: 06a83704c3c3c80871706c16f45cf9d17600628a9f11727e847a540f059a2d2b

build:
  number: 0
  noarch: python
  entry_points:
    - tabulator = tabulator.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - cchardet >=1.0,<2.0
    - click >=6.0,<7.0
    - ijson >=2.0,<3.0
    - jsonlines >=1.1,<2.0
    - linear-tsv >=1.0,<2.0
    - openpyxl >=2.4,<2.5
    - python
    - requests >=2.8,<3.0
    - six >=1.9,<2.0
    - sqlalchemy >=0.9.6,<2.0
    - unicodecsv >=0.14,<2.0
    - xlrd >=1.0,<2.0

test:
  imports:
    - tabulator
    - tabulator.loaders
    - tabulator.parsers
    - tabulator.writers
  commands:
    - tabulator --help
  requires:
    - pylama
    - tox

about:
  home: https://github.com/frictionlessdata/tabulator-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Consistent interface for stream reading and writing tabular data (csv/xls/json/etc)

extra:
  recipe-maintainers:
    - ocefpaf
