travis:
  secure:
    BINSTAR_TOKEN: bwxhfjFOZ6gX4ZDbfN9HDz5wjd0SdC3XpLsXCITx3tIrYrZ5ocI2KTgwGU6TPj3H75QVSdXWSZ9w7MrmpHnMjAtt9dyk3MNHT8YSgzx9L6+9SxL51PJ8i4EVKpJtVzsz9FKyVF+gw6zO5S5iG6aR+M0+6Hs0YcP+Hrd+ER9fiQ/trA6pSZlNOOG8K68qlnAZ0Vxs12sjmyv+2NYuMmS7B2i3jktnyMUyLP+blZ1xdNHWLnWlKRY5aVIijEzGl2Gw8+LsrfWv701WrjgSXqg4F3TpFuHOWZoB1dyqYxImB6GJpoZyJuNaQfNXJopzmAJXBO694SOlkMsXPDLuWVFXLSghP/VyfTXLL/+MdgJ+qhFHGtXWNtcqPkNgQgfsznxA04gaaSIws6sdjLnjGqQrvJBOhCJ2UPWNlPoJ+q8sV9DRrV3dKQwVMP3NoNkunyBVMwF4sd+SZAsEJFmwDfJQe24bjJxmsBMqnPmHmQSpCSffn3vLpfiTMliiBlgcsE+EDwx7OdQX6rznd/qQyCcvo1o4/hAwwZp69qQ6f/qobnjrCM6Cl/dEZQYM68XSR/SoFABrkE1BmNDQ7D25k2ayDw5kHwR9SpeTvwL1O2paKtx+xZ7Z1GwF7+tavxFKBaSu1NO8TM8V2XjWUVrVV+nGD/BQABG3mTVDR+oCqOu/6To=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
