travis:
  secure:
    BINSTAR_TOKEN: gFX6wZtj3THUuubYeZlGLQRkFbFn1x43pLuccFxm5qLjqUsTu4DDh7ibRaaPtYTwGb76ztp1lzNP3zMSiNf2yZXTvGoGESKBmSzmkYA4NYuMYjEteFZVPBA7bqLWacj0/5O+ioU4bAPBOJaWY9Z4ereEECf1/j+eaiFhJj1gMn985bs49SkpZjP22jyydrHt8naFsO+6DFx2NKdTLDJSWKdBwhAmE3shEWys4NUCTYPck4iwVD34JOjkIUNG+FxJGTEDz6uyAGDtFThvFPuG/+JZhI3pjmM9peWY8IBjVE6hMMh1JL56PkSu56p1UkdcBD+0LBpaE//ihjB6KCk8CcO41VwTnLR40DiXJTHkw2FjJeftwWNVaQXxef8OEnp0brfIRYTmF1ljmbE6MVt9/mcGmN10Qlbyf8rkG75FldlU3XjSzx3Hkw7cCSpcL3kK9qAGU2a+CbhiD2WhGwHNkXCd65LOO3uO0Uvc+2m1tL9bykzqSzZ6gzi3/YXIR7Gn1XpRoeWJk4fy/m0hGS1bqHVPTVMADKxO8Gz66fIdHSLE5voqZhpG43LMy1BujT4FJFXJdvF+KvzrNqJmaX5iQhw4rQ6IAEPACVnNP6PZQBF5Ki3YftqTLXr7697gda2vnnNrZevCd7b4jF0fuQ4vPYJDY9UJa0Zw93IJvJS2FWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
